### PR TITLE
Adding an index on notifier_properties

### PR DESCRIPTION
**Pull request by dnavre**
I changed the approach used in flyway script naming. when reviewing please pay particular attention to that.

### CODE REVIEW

**Review by mikron — CHANGES_REQUESTED** [review]
Please create alternative idx also for MySQL

**Comment by dnavre** [comment]
> Please create alternative idx also for MySQL

I think that probably won't be required cause it creates indexes for FKs automatically.

**Review by mikron — CHANGES_REQUESTED** [review]
Flyway refuses to apply validation, please use the projects versioning model, instead of logically correct one :) 

`Validate failed: Detected resolved migration not applied to database: 1.10.1`

**Comment by dnavre** [comment]
> Flyway refuses to apply validation, please use the projects versioning model, instead of logically correct one :)
> 
> `Validate failed: Detected resolved migration not applied to database: 1.10.1`

done :) Sorry for the hassle.

**Review by mikron — APPROVED** [review]

**Pull request merged**
